services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./lib/database/.env
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
    driver: local
